---
title: R Fundamentals II
subtitle: Introduction to R for non-programmers
---


We will first recapitulate the concepts learned in the previous module. Then building on that, you will learn more about plots, including saving graphs in different types of files. Furthermore, 
you will learn how to write and understand functions, what are the control flow structures in R and how to export data. Installing and using R packages will also be covered.

Date: 12-01-2020

Instructor: Hana Ševčíková

Assistents: Christy Lam, Suzanne Childress, Polina Butina

## Prerequisites
If you attended the first module, you should have everything you need. Otherwise, please follow [these Prerequisites instructions](https://psrc.github.io/r-basics-I/00-index.html).

## Topics

1. [More plots](01-more-plots.html)
2. [Writing data](02-writing-data.html)
3. [Functions](03-functions.html)
4. [Control flow](04-control-flow.html)
5. [Installing packages](05-packages.html)
6. [Homework](06-home-work.html)

<br>
<br>
<br>
<br>
<br>
<br>



