---
layout: page
title: R Fundamentals II
subtitle: Homework
---

```{r, include=FALSE}
source("tools/chunk-options.R")
opts_chunk$set(fig.path = "fig/06-home-work-")
fence <- function(text, wrapper){
    text <- c(wrapper, text, wrapper)
    result <- paste0(text, collapse = " ")
    return(result)
}
growth.rate <- function(x, y) {
    rate <- (y - x)/x * 100
    return(rate)
}
add.growth.rate <- function(dat, col1, col2, new.name = "GrowthRate") {
    newcol <- growth.rate(dat[, col1], dat[, col2])
    dat[[new.name]] <- round(newcol, 1)
    return(dat)
}

hh <- read.table(file="data/cities_households.csv", header=TRUE, sep=",")
cities <- read.csv(file="data/cities.csv")
hh <- merge(hh, cities, by="city_id", all=TRUE)

hhgr <- add.growth.rate(hh, "hh2020", "hh2030")

```

> ## Challenge 1 {.challenge}
>
> The `paste` function can be used to combine text together, e.g:
>
> ```{r}
> best_practice <- c("Write", "programs", "for", "people", "not", "computers")
> paste(best_practice, collapse=" ")
> ```
>
>  Write a function called `fence` that takes two vectors as arguments, called
> `text` and `wrapper`, and prints out the text wrapped with the `wrapper`:
>
> ```{r}
> fence(text = best_practice, wrapper = "***")
> ```
>
> *Note:* the `paste` function has an argument called `sep`, which specifies the
> separator between text. The default is a space: " ". The default for `paste0`
> is no space "".
>

> ## Challenge 2 {.challenge}
> Can you write a `for` loop that reproduces the following 4-panel plot of growth rate 
> from 2020 to 2030 for the four counties?
>
> ```{r, echo = FALSE}
> par(mfrow = c(2,2))
> for(cnty in c("King", "Kitsap", "Pierce", "Snohomish")){
>    s <- subset(hhgr, county_name == cnty)
>    hist(s$GrowthRate, main = cnty, xlab = "HH Growth 2020-2030")
> }
> ```
> _Hint_: See the [Saving Plots](01-more-plots.html#saving-plots) section on creating a 2x2 graph panels.
> 


> ## Challenge 3 {.challenge}
>
> Prepare for the next module by installing the required packages:
> `tidyverse`, `openxlsx`, `scales`, `plotly`, `reshape2`, `lubridate`, `htmlwidgets`
>